version: "3.9"
services:
  web-app:
    build: .
    ports:
      - "8000:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
        # Development certificate for TLS
      - ASPNETCORE_Kestrel__Certificates__Default__Password=PASSWORD
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/_AWESOME_SPA_.pfx
    volumes:
      # Development certificate volume
      - ~/.aspnet/https:/https:ro
    //#if(UsePostgreSql)
    networks:
      - postgres
    //#endif

networks:
  postgres:
    name: "postgres_db"
    external: true

